# Generated by Django 2.1.5 on 2019-05-29 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('level', models.CharField(choices=[('none', 'Select Level'), ('kinder', 'Kindergarten'), ('sped', 'SPED'), ('als_reading', 'Alternative Reading Class'), ('als_tutorial', 'Alternative Tutorial Class'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12'), ('college_1', 'First Year College'), ('college_2', 'Second Year College'), ('college_3', 'Third Year College'), ('college_4', 'Fourth Year College')], default='none', max_length=100)),
                ('school_last_attended', models.CharField(max_length=200)),
                ('school_current', models.CharField(max_length=200)),
                ('date_ikp_enrollment', models.DateField()),
                ('sponsors_name', models.CharField(max_length=100)),
                ('student_bio', models.TextField()),
                ('educational_status', models.CharField(choices=[('none', 'Select Status'), ('pr_graduated', 'Graduated'), ('pr_pending_test', 'Waiting for Accreditation and Equivalency Test Result'), ('pr_retained', 'Retained'), ('pr_retained_inactive', 'Retained, Inactive'), ('pr_grade_1', 'Grade 1'), ('pr_grade_2', 'Grade 2'), ('pr_grade_3', 'Grade 3'), ('pr_grade_4', 'Grade 4'), ('pr_grade_5', 'Grade 5'), ('pr_grade_6', 'Grade 6'), ('pr_grade_7', 'Grade 7'), ('pr_grade_8', 'Grade 8'), ('pr_grade_9', 'Grade 9'), ('pr_grade_10', 'Grade 10'), ('pr_grade_11', 'Grade 11'), ('pr_grade_12', 'Grade 12'), ('pr_college_1', 'First Year College'), ('pr_college_2', 'Second Year College'), ('pr_college_3', 'Third Year College'), ('pr_college_4', 'Fourth Year College')], default='none', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
