# Generated by Django 2.1.5 on 2019-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0002_auto_20190702_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='parent_guardian_1',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='parent_guardian_2',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
