# Generated by Django 2.1.5 on 2019-05-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0002_studentinfo_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='profile_image',
            field=models.ImageField(default='uploads/image/default_none.png', upload_to='uploads/image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='educational_status',
            field=models.CharField(choices=[('None', 'Select Status'), ('Graduated', 'Graduated'), ('Waiting for Accreditation and Equivalency Test Result', 'Waiting for Accreditation and Equivalency Test Result'), ('Retained', 'Retained'), ('Retained, Inactive', 'Retained, Inactive'), ('Promoted to Grade 1', 'Promoted to Grade 1'), ('Promoted to Grade 2', 'Promoted to Grade 2'), ('Promoted to Grade 3', 'Promoted to Grade 3'), ('Promoted to Grade 4', 'Promoted to Grade 4'), ('Promoted to Grade 5', 'Promoted to Grade 5'), ('Promoted to Grade 6', 'Promoted to Grade 6'), ('Promoted to Grade 7', 'Promoted to Grade 7'), ('Promoted to Grade 8', 'Promoted to Grade 8'), ('Promoted to Grade 9', 'Promoted to Grade 9'), ('Promoted to Grade 10', 'Promoted to Grade 10'), ('Promoted to Grade 11', 'Promoted to Grade 11'), ('Promoted to Grade 12', 'Promoted to Grade 12'), ('Promoted to First Year College', 'Promoted to First Year College'), ('Promoted to Second Year College', 'Promoted to Second Year College'), ('Promoted to Third Year College', 'Promoted to Third Year College'), ('Promoted to Fourth Year College', 'Promoted to Fourth Year College')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('None', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='level',
            field=models.CharField(choices=[('None', 'Select Level'), ('Kindergarten', 'Kindergarten'), ('SPED', 'SPED'), ('Alternative Reading Class', 'Alternative Reading Class'), ('Alternative Tutorial Class', 'Alternative Tutorial Class'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('First Year College', 'First Year College'), ('Second Year College', 'Second Year College'), ('Third Year College', 'Third Year College'), ('Fourth Year College', 'Fourth Year College')], default='None', max_length=100),
        ),
    ]
