# Generated by Django 2.2.1 on 2019-07-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0002_auto_20190715_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='educational_status',
            field=models.CharField(choices=[('None', 'Select Status'), ('General Promotions', (('Graduated', 'Graduated'), ('Waiting for Accreditation and Equivalency Test Result', 'Waiting for Accreditation and Equivalency Test Result'), ('Recommended for Philippine Educational Placement Test', 'Recommended for Philippine Educational Placement Test'), ('Retained', 'Retained'), ('Retained; Active', 'Retained; Active'), ('Retained; Inactive', 'Retained; Inactive'), ('Promoted', 'Promoted'), ('Promoted (Status Quo)', 'Promoted (Status Quo)'))), ('Pre-School Promotions', (('Promoted to Kindergarten', 'Promoted to Kindergarten'), ('Promoted to Kindergarten A', 'Promoted to Kindergarten A'), ('Promoted to Kindergarten B', 'Promoted to Kindergarten B'))), ('Grade School Promotions', (('Promoted to Grade 1', 'Promoted to Grade 1'), ('Promoted to Grade 2', 'Promoted to Grade 2'), ('Promoted to Grade 3', 'Promoted to Grade 3'), ('Promoted to Grade 4', 'Promoted to Grade 4'), ('Promoted to Grade 5', 'Promoted to Grade 5'), ('Promoted to Grade 6', 'Promoted to Grade 6'))), ('Junior High School Promotions', (('Promoted to Grade 7', 'Promoted to Grade 7'), ('Promoted to Grade 8', 'Promoted to Grade 8'), ('Promoted to Grade 9', 'Promoted to Grade 9'), ('Promoted to Grade 10', 'Promoted to Grade 10'))), ('Senior High School Promotions', (('Promoted to Grade 11', 'Promoted to Grade 11'), ('Promoted to Grade 12', 'Promoted to Grade 12'))), ('College Promotions', (('Promoted to First Year College', 'Promoted to First Year College'), ('Promoted to Second Year College', 'Promoted to Second Year College'), ('Promoted to Third Year College', 'Promoted to Third Year College'), ('Promoted to Fourth Year College', 'Promoted to Fourth Year College')))], default='None', max_length=100),
        ),
    ]
