# Generated by Django 2.1.5 on 2019-07-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0003_auto_20190710_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='parent_civil_status',
            field=models.CharField(choices=[('None', 'Select Civil Status'), ('Married', 'Married'), ('Separated', 'Separated'), ('Widow/Widower', 'Widow/Widower'), ('Solo', 'Solo'), ('Common Law', 'Common Law')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='parent_guardian_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='parent_guardian_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='school_current',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='school_last_attended',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='section',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sponsors_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student_bio',
            field=models.TextField(max_length=1000),
        ),
    ]
