# Generated by Django 2.1.5 on 2019-05-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0003_auto_20190530_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='profile_image',
            field=models.ImageField(default='uploads/image/default_none.png', upload_to='uploads/'),
        ),
    ]
