# Generated by Django 2.1.5 on 2019-05-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0004_auto_20190530_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='profile_image',
            field=models.ImageField(default='default_none.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
