# Generated by Django 2.1.5 on 2019-06-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0005_auto_20190530_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='course',
            field=models.CharField(choices=[('None', 'None')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='section',
            field=models.CharField(default='Not Applicable', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='educational_status',
            field=models.CharField(choices=[('None', 'Select Status'), ('Graduated', 'Graduated'), ('Waiting for Accreditation and Equivalency Test Result', 'Waiting for Accreditation and Equivalency Test Result'), ('Recommended for Philippine Educational Placement Test', 'Recommended for Philippine Educational Placement Test'), ('Retained', 'Retained'), ('Retained; Active', 'Retained; Active'), ('Retained; Inactive', 'Retained; Inactive'), ('Promoted', 'Promoted'), ('Promoted (Status Quo)', 'Promoted (Status Quo)'), ('Promoted to Kindergarten', 'Promoted to Kindergarten'), ('Promoted to Kindergarten A', 'Promoted to Kindergarten B'), ('Promoted to Kindergarten A', 'Promoted to Kindergarten B'), ('Promoted to Grade 1', 'Promoted to Grade 1'), ('Promoted to Grade 2', 'Promoted to Grade 2'), ('Promoted to Grade 3', 'Promoted to Grade 3'), ('Promoted to Grade 4', 'Promoted to Grade 4'), ('Promoted to Grade 5', 'Promoted to Grade 5'), ('Promoted to Grade 6', 'Promoted to Grade 6'), ('Promoted to Grade 7', 'Promoted to Grade 7'), ('Promoted to Grade 8', 'Promoted to Grade 8'), ('Promoted to Grade 9', 'Promoted to Grade 9'), ('Promoted to Grade 10', 'Promoted to Grade 10'), ('Promoted to Grade 11', 'Promoted to Grade 11'), ('Promoted to Grade 12', 'Promoted to Grade 12'), ('Promoted to First Year College', 'Promoted to First Year College'), ('Promoted to Second Year College', 'Promoted to Second Year College'), ('Promoted to Third Year College', 'Promoted to Third Year College'), ('Promoted to Fourth Year College', 'Promoted to Fourth Year College')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='level',
            field=models.CharField(choices=[('None', 'Select Level'), ('Kindergarten', 'Kindergarten'), ('Kindergarten A', 'Kindergarten A'), ('Kindergarten B', 'Kindergarten B'), ('SPED', 'SPED'), ('Alternative Reading Class', 'Alternative Reading Class'), ('Alternative Tutorial Class', 'Alternative Tutorial Class'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 7 (ALS)', 'Grade 7 (ALS)'), ('Grade 7 (Open High)', 'Grade 7 (Open High)'), ('Grade 8', 'Grade 8'), ('Grade 8 (ALS)', 'Grade 8 (ALS)'), ('Grade 8 (Open High)', 'Grade 8 (Open High)'), ('Grade 9', 'Grade 9'), ('Grade 9 (ALS)', 'Grade 9 (ALS)'), ('Grade 9 (Open High)', 'Grade 9 (Open High)'), ('Grade 10', 'Grade 10'), ('Grade 10 (ALS)', 'Grade 10 (ALS)'), ('Grade 10 (Open High)', 'Grade 10 (Open High)'), ('Grade 11', 'Grade 11'), ('Grade 11 (ALS)', 'Grade 11 (ALS)'), ('Grade 11 (Open High)', 'Grade 11 (Open High)'), ('Grade 12', 'Grade 12'), ('Grade 12 (ALS)', 'Grade 12 (ALS)'), ('Grade 12 (Open High)', 'Grade 12 (Open High)'), ('First Year College', 'First Year College'), ('Second Year College', 'Second Year College'), ('Third Year College', 'Third Year College'), ('Fourth Year College', 'Fourth Year College')], default='None', max_length=100),
        ),
    ]
