# Generated by Django 2.1.5 on 2019-07-10 11:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0006_auto_20190710_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='child_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Orphaned', 'Orphaned'), ('Neglected', 'Neglected'), ('Abandoned', 'Abandoned'), ('Abused (Physically/Sexually)', 'Abused (Physically/Sexually)'), ('Trafficked', 'Trafficked'), ('Child in Conflict with the Law (CICL)', 'Child in Conflict with the Law (CICL)')], max_length=100),
        ),
    ]
