# Generated by Django 2.1.5 on 2019-06-12 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0006_auto_20190603_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='date_ikp_enrollment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='school_current',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='school_last_attended',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sponsors_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student_bio',
            field=models.TextField(default='Add a description'),
        ),
    ]
