# Generated by Django 2.2.1 on 2019-07-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0007_auto_20190710_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='profile_image',
            field=models.ImageField(default='default_none.png', upload_to='uploads/avatar/'),
        ),
    ]
