# Generated by Django 2.2.1 on 2019-07-14 15:04

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ikp_sis', '0008_auto_20190714_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='profile_image',
            field=sorl.thumbnail.fields.ImageField(default='default_none.png', upload_to='uploads/avatar/'),
        ),
    ]
